### ISSUE TITLE
Please add Scroll feature for large list of items

### ISSUE THREAD

**Issue by arunavo4** [arcadefire/nice-spinner#103]
##Feature Request
add Scroll feature for large list of items and give an option for min number of items in view

**Comment by SudoAjay** [comment]
yes we want Scroll Feature :) :)

**Comment by arcadefire** [comment]
Added in a484fe55b883d29578f2d05ff23cc9af82efe10f

**Comment by Marcosmaliki** [comment]
Still can't scroll @arcadefire
