### ISSUE TITLE
arrow animation not reset after view disabled

### ISSUE THREAD

**Issue by erlangp** [arcadefire/nice-spinner#105]

**Comment by erlangp** [comment]
screenshot: https://imgur.com/a/gnUBCHx

**Comment by erlangp** [comment]
how to cancel arrow animation & make arrow down after call `.setEnable(false)` ?

**Comment by arcadefire** [comment]
Hello @erlangp, how can I reproduce the issue?

**Comment by arcadefire** [comment]
This should be fixed in this commit: 9e18b1f35f5d7017e3affe34e73b37e02c97ba2b.

**Comment by erlangp** [comment]
thanks sir @arcadefire
