### ISSUE TITLE
ClassCastException with Appcompat module

### ISSUE THREAD

**Issue by falkontre** [arcadefire/nice-spinner#12]
Hi Angelo,

It seems that the spinner triggers an Exception if the project uses the Appcompat library (com.android.support:appcompat-v7:23.0.0)

java.lang.ClassCastException: android.support.v7.widget.AppCompatSpinner cannot be cast to org.angmarch.views.NiceSpinner

**Comment by falkontre** [comment]
Sorry, I've used <Spinner...> in my layout instead of <org.angmarch.views.NiceSpinner>

**Comment by arcadefire** [comment]
Doon't worry! :+1:
