### ISSUE TITLE
Some Drop down Items are not shown

### ISSUE THREAD

**Issue by tanoDxyz** [arcadefire/nice-spinner#120]
while using **androidX** and everything was OK but when i used the spinner in layout that was inflated for a Dialog. some drop down items were not shown. 
Layout structure is 

**RelativeLayout 
                         Linear Layout
                                                Spinner**

**Comment by arcadefire** [comment]
Can you post a screenshot?

**Comment by tanoDxyz** [comment]
![c_1_50](https://user-images.githubusercontent.com/33701127/58500088-e9dc8200-819a-11e9-8654-563bb9f564bf.png)


**used xml attribute @entries ... which contains 8 elements**

**Comment by arcadefire** [comment]
It's most probably cut by the dialog's window. I don't plan to investigate that, but feel free to open a PR if you find a solution. :)
