### ISSUE TITLE
I get an error when I use it in popupWindow

### ISSUE THREAD

**Issue by GiveSmile** [arcadefire/nice-spinner#122]
hello
   The specific error log is shown below：
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@3b3e561c is not valid; is your activity running?

**Comment by arcadefire** [comment]
Can you give me more detailed instructions on how to reproduce it?

**Comment by GiveSmile** [comment]
I tried to set a nice-spinner in a PopWindow that was already displayed, and then an error occurred when I clicked it again   
![图片](https://user-images.githubusercontent.com/45993544/58696021-47eeac80-83c9-11e9-8c8d-07bd170e2ac7.png)
Thanked your reply

**Comment by arcadefire** [comment]
I don't think this is directly related to the spinner. I'm not planning to investigate this further, though. Feel free to open a PR if you discover the issue. :)
