### ISSUE TITLE
Textview do not display text when there is only one item of data

### ISSUE THREAD

**Issue by carrot-wen** [arcadefire/nice-spinner#127]
I modified the demo code to reproduce this problem：
![20190703100536](https://user-images.githubusercontent.com/21718680/60558911-6c99c380-9d7d-11e9-8859-72743195e5a3.png)
![20190703102859](https://user-images.githubusercontent.com/21718680/60558933-7a4f4900-9d7d-11e9-8f56-420073069d46.png)

note:  i fixd this problem by modifying NiceSpinner#setAdapterInternal and changing  `if (adapter.getCount() > 0)` to `if (adapter.getCount() >= 0)`。
Hope this helps you

**Comment by 444601385** [comment]
NiceSpinner niceSpinner = (NiceSpinner) findViewById(R.id.nice_spinner);
 List<String> dataset = new LinkedList<>(Arrays.asList("One"));
 niceSpinner.attachDataSource(dataset);
 niceSpinner.setText(dataset.get(0));

**Comment by 444601385** [comment]
NiceSpinner NiceSpinner = (NiceSpinner) findViewById (R.id.nice_spinner);
列表数据集= new LinkedList < > (arrays . aslist(“一”));
niceSpinner.attachDataSource(数据集);
niceSpinner.setText (dataset.get (0));

**Comment by 444601385** [comment]
NiceSpinner NiceSpinner = (NiceSpinner) findViewById (R.id.nice_spinner);
List<String> dataset= new LinkedList < > (arrays . aslist(“One”));
niceSpinner.attachDataSource(dataset);
niceSpinner.setText (dataset.get (0));

**Comment by carrot-wen** [comment]
I understand, thank you.

**Comment by cuncaojin** [comment]
i find the repository's newest lib ,just v1.4.3 is also have this question.  if the item data is an object ? waht to do?
