### ISSUE TITLE
upload to maven 

### ISSUE THREAD

**Issue by KingOfBeer** [arcadefire/nice-spinner#13]
good work there... can you upload it to mavencentral?

**Comment by arcadefire** [comment]
Sure, I will do this asap! :)

**Comment by Andecy** [comment]
@arcadefire mavenCentral ...please

**Comment by jaredrummler** [comment]
I used this repo as a base and uploaded it to maven central. 

https://github.com/jaredrummler/Material-Spinner 

It has RTL support and the ability to set the background and text colors (spinner looked bad on dark themes).

**Comment by arcadefire** [comment]
I've uploaded this library on JitPack. The details to include it in your project are in the updated readme file.
