### ISSUE TITLE
PopupMenu Background color

### ISSUE THREAD

**Issue by mrtarunsaraswat** [arcadefire/nice-spinner#146]
How can I change the popup menu background color? By default it is white.

**Comment by tachyonlabs** [comment]
Having just done this myself, you use the `backgroundSelector` attribute. For example, in the drawable directory I created a file spinner_background_selector.xml with contents of 
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@color/colorDayNightSpinnerBackground" />
</selector>
```
and in my layout file added this attribute to the spinners:
`app:backgroundSelector="@drawable/spinner_background_selector"`

**Comment by ColdSongDvl** [comment]
If there are two NiceSpinners in the ui and use this property, it will cause arrow confusion
