### ISSUE TITLE
text color of each item not changing

### ISSUE THREAD

**Issue by vigneswarandavarapu** [arcadefire/nice-spinner#19]
i am using your library in my project.but text color not changing.even iam using  NiceSpinnerAdapterWrapper.please solve my problem

![mobogenie_20151218_143303](https://cloud.githubusercontent.com/assets/14231307/11893205/af847634-a594-11e5-99d5-e87bb36ef275.png)
![mobogenie_20151218_143324](https://cloud.githubusercontent.com/assets/14231307/11893206/afd6ff26-a594-11e5-90a4-59caca59122f.png)

**Comment by SusionSuc** [comment]
the same problem

**Comment by SusionSuc** [comment]
By modify a little source code, I have solve this problem. I don't have time to find more.

  public View getView(int position, View convertView, ViewGroup parent) {
        TextView textView;

        if (convertView == null) {
            convertView = View.inflate(mContext, R.layout.spinner_list_item, null);
            textView = (TextView) convertView.findViewById(R.id.tv_tinted_spinner);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
                textView.setBackground(ContextCompat.getDrawable(mContext, mBackgroundSelector));
            }

            convertView.setTag(new ViewHolder(textView));
        } else {
            textView = ((ViewHolder) convertView.getTag()).textView;
        }

        textView.setText(getItem(position).toString());
       // textView.setTextColor(mTextColor);        
        textView.setTextColor(Color.BLACK);    //here
        return convertView;
}

when use:   
niceSpinnerType.attachDataSource(datasetType);
niceSpinnerType.setTextColor(Color.BLACK);
niceSpinnerType.setLinkTextColor(Color.BLACK);

**Comment by pcegarra** [comment]
Thank you SusionSuc

**Comment by khalifaqwame** [comment]
use the following code in your layout xml  
app:textTint="@color/black"

**Comment by arcadefire** [comment]
This should've been solved with 97c610075530bfcd09fbf0d7efaf5ba632ad20f1. 👍 
Closing this for now, feel free to reopen it if the issue persists.
