### ISSUE TITLE
Suggestion: Make the API similar to android.widget.Spinner

### ISSUE THREAD

**Issue by curioustechizen** [arcadefire/nice-spinner#2]
This is a great widget. I've noticed that the default Spinner that comes with the design library is a bit confusing for users.

I have a suggestion: make the API of `NiceSpinner` compatible with `android.widget.Spinner` so that it acts as a so-called "drop-in replacement". This includes stuff like using `setAdapter` instead of `attachDataSource` and using `setOnItemSelectedListener` instead of `setOnItemClickListener` (the latter is not supported by `Spinner`). This will make it much easier for devs to use `NiceSpinner` (basically a search and replace will do).

**Comment by arcadefire** [comment]
Hello @curioustechizen, it's a great idea, I will add these methods in the next iteration!

**Comment by arcadefire** [comment]
I've added the `onSelectedListener` support plus `setAdapter` in the last commits. For now I leave this open. If you can list all these methods it would be great make NiceSpinner to support (I don't think it would be necessary to implement them all).

**Comment by curioustechizen** [comment]
In my experience the two that you have already implemented are the most common methods used with a Spinner. I would leave the rest as lower priority :-)

**Comment by arcadefire** [comment]
Thank you for your feedbacks! :)

**Comment by Baneeishaque** [comment]
please add setSelection(positiion) method...
