### ISSUE TITLE
The problem with the arrow

### ISSUE THREAD

**Issue by XinYiWorld** [arcadefire/nice-spinner#22]
I used nice-spinner  in a project ,the arrow is normal;however,when i used it in another project,the direction of the arrow is to left,and the drawable of the arrow changed?please help me out,thanks!
![aaaaaaa](https://cloud.githubusercontent.com/assets/14458960/15662484/d14c83e0-2723-11e6-90e4-c3d19a400b6b.png)

**Comment by XinYiWorld** [comment]
Can it be the diffferent themes of my app results in the problem?

**Comment by arcadefire** [comment]
Hello @XinYiWorld, I cannot really tell what is your problem, the screenshot is really small.

**Comment by passionfun** [comment]
arrowDrawable method is not effect，why？

**Comment by passionfun** [comment]
I want to use my arrow picture,but arrowDrawable method is not useless!can you tell me why?
