### ISSUE TITLE
Avoid Repeatation of background in adapter

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [arcadefire/nice-spinner#24]
I am trying to use android:background="@drawable/box_edittext2" but it did not work and If I try to to put this in JAVA it repeat the background for each row ... is it possible to put adapter's row background different and NiceSpinner Background differnet

**Comment by arcadefire** [comment]
It's not possible right now, I'll give a look into it.

**Comment by arcadefire** [comment]
That's not supported right now, but feel free to open a PR. :)
