### ISSUE TITLE
Android Compatibility

### ISSUE THREAD

**Issue by lolobosse** [arcadefire/nice-spinner#3]
Hi there,

While testing your project I found two bugs happening with `Sony ST2i` running `Android 4.0.4` (`15`). The fist seems easy to solve it's a matter of color, the color of the selected spinner is not set gradually: you directly something grey like this:

![issue1](https://cloud.githubusercontent.com/assets/5024077/9060890/29349830-3ab8-11e5-99e3-e096fdffc750.png)

The second issue is more critical, you cannot select a displayed value on this phone, the click do not respond...
Step to reproduce:
- Click on the spinner
- Click on proposed values
  Expected behaviour:
- Value is selected and replaces the old-selected value.
  Current behaviour:
- Nothing happens

BTW: I created a project with a sample which compiles directly when you put it in Android Studio (I fixed some bugs of yours). If someone is interested: https://github.com/lolobosse/nice_spinner_demo

**Comment by arcadefire** [comment]
Hey @lolobosse, nice one! I will investigate on these. The main issue is that I have no access to Icecream devices, so I might take a while. If you discover some way to fix these, feel free to approach me or do a PR! :)

**Comment by lolobosse** [comment]
I think it could be possible to reproduce that in emulator.
Try that out and I've an access to some 4.0.x devices, so I'll try to figure out what's going on ...

**Comment by arcadefire** [comment]
That second one (the critical) should be solved with 7859190131248f2248b15762c050f669c6754add, can you check?

**Comment by lolobosse** [comment]
Cannot yet, I'm on holidays in the middle of Scotland without internet and
without my API 15 device...

I'm back in two weeks
Am 08.08.2015 1:34 nachm. schrieb "Angelo Marchesin" <
notifications@github.com>:

**Comment by i-Rohan** [comment]
How do I include this library in my project. what should I add in 'build.gradle'?

**Comment by lolobosse** [comment]
@i-Rohan 
1. Please create a separate issue for that
2. There is no gradle build that I know, you have to clone and include as a submodule.

**Comment by arcadefire** [comment]
I'm not sure if this I still valid, any news?

**Comment by lolobosse** [comment]
@arcadefire: no idea, I'll try to give a try in the next days. I'm at the office tomorrow
