### ISSUE TITLE
Why the item center inside？

### ISSUE THREAD

**Issue by hugoFather** [arcadefire/nice-spinner#30]
i click the item found that the inner text of the item is center，can you help me?thank you

**Comment by arcadefire** [comment]
Hello, what's the issue exactly? You'd like an option to choose the text alignment?

**Comment by hugoFather** [comment]
The default item（Clicked Item）is not centered， but the text in the item is automatically centered when the spinner drop down。It looks very strangle，Why not all in center or not in center both Item？Thank you，although i have been change other style，i really want to know why。
