### ISSUE TITLE
how to change textSize？

### ISSUE THREAD

**Issue by wshx21** [arcadefire/nice-spinner#33]
how to change textSize？

**Comment by arcadefire** [comment]
You can't at the moment, I'll try to push an update to solve this issue.

**Comment by wshx21** [comment]
thank you

**Comment by wshx21** [comment]
you can creat a inerface to change item layout

**Comment by GitCod-Man** [comment]
@arcadefire 
I want to changge the NiceSpinner's border ,and i try to set the background with shape.xml ,but it didn't work!
<org.angmarch.views.NiceSpinner
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:spinnerMode="dialog"
android:id="@+id/nice_spinner"
android:layout_gravity="center"
android:background=""
android:layout_marginRight="20dp"
android:layout_marginLeft="20dp"
android:layout_marginTop="20dp"
/>

**Comment by chenhon** [comment]
you can overwrite spinner_list_item.xml in your layout file.
