### ISSUE TITLE
Constraint layout stops rendering

### ISSUE THREAD

**Issue by mehul4795** [arcadefire/nice-spinner#34]
When this library is used, the constraint layout stops rendering.

**Comment by arcadefire** [comment]
Please, add some details/screenshot.

**Comment by KaiserPerwez** [comment]
![error](https://user-images.githubusercontent.com/22406803/27762134-1ed63eec-5e89-11e7-995f-c08996d438d0.png)
![image](https://user-images.githubusercontent.com/22406803/27762142-3ccde378-5e89-11e7-95f5-b9ea7c6e31a1.png)

**Comment by karanthakakr04** [comment]
I am facing this same issue. This repo breaks the constraints layout. No matter what you do it won't work.

**Comment by arcadefire** [comment]
It works fine on my machine. 
<img width="355" alt="screen shot 2017-07-08 at 23 49 11" src="https://user-images.githubusercontent.com/3945083/27989400-14af0278-6438-11e7-82ce-d8964b5d4c5d.png">

Can you maybe upload a repo with a sample project showing the bug and link this repo here?

**Comment by hanmeimei888** [comment]
i'm facing this issue too
      repo here:

Rendering failed with a known bug. Please try a rebuild.  The following classes could not be instantiated:
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
- org.angmarch.views.NiceSpinner (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NoSuchFieldError: ViewBackgroundHelper   at android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:46)   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:63)   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)   at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:52)   at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:46)   at com.android.layoutlib.bridge.impl.Layout.createNavBar(Layout.java:284)   at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:140) Copy stack to clipboard

**Comment by hanmeimei888** [comment]
`Rendering failed with a known bug. Please try a rebuild.  The following classes could not be instantiated:
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
- org.angmarch.views.NiceSpinner (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NoSuchFieldError: ViewBackgroundHelper   at android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:46)   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:63)   at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)   at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:52)   at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:46)   at com.android.layoutlib.bridge.impl.Layout.createNavBar(Layout.java:284)   at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:140) Copy stack to clipboard  `

**Comment by hanmeimei888** [comment]
![3 y 0d b787h7 w euf r6](https://user-images.githubusercontent.com/25998847/28153130-632686e6-67d6-11e7-9bd2-63d78b7ab2a5.png)
this is the mistake studio repo

**Comment by hanmeimei888** [comment]
and i solve it by change compileSdkVersion 23  --> compileSdkVersion 24

**Comment by hanmeimei888** [comment]
@karanthakakr04 @arcadefire

**Comment by hanmeimei888** [comment]
ps: i have 0 followers now ,could you click following for me ? It's just a cutie's hope...

**Comment by tsakmalis** [comment]
I have the same problem, have you found any solution?
