### ISSUE TITLE
Spinner open towards the top

### ISSUE THREAD

**Issue by ezekielchow** [arcadefire/nice-spinner#35]
For some reason, the spinner open towards the top covering the other components.

![screenshot_2017-06-13-20-48-41-297_com example ezekielchow foodorder_mvp](https://user-images.githubusercontent.com/4429691/27083267-92a7fe54-507a-11e7-97f6-64ec3c49f7d7.png)

**Comment by 1037390459** [comment]
This would happen if the item which inflates the spinner is close to the bottom of the screen.

**Comment by TongZhang1314** [comment]
No, I'm spinner in the top still has this problem

**Comment by jonydan888** [comment]
Hey, @TongZhang1314 

This problem you modify the 2 values in the demens file can be done, which is written in this value, resulting in the height can not be customized, self-adaptive.
    <dimen name="three_grid_unit">12dp</dimen>
    <dimen name="one_and_a_half_grid_unit">24dp</dimen>

**Comment by passself** [comment]
Hey,@jonydan888, I changed dimens, It still has this problem

**Comment by arcadefire** [comment]
This should be fixed in the last releases.
