### ISSUE TITLE
crash when using in dialog

### ISSUE THREAD

**Issue by hanmeimei888** [arcadefire/nice-spinner#39]
![normal useinactivity](https://user-images.githubusercontent.com/25998847/28257795-f4bf663c-6aff-11e7-8555-22d106c995d1.png)
it's use in normal activity   all is well 

and then 
![crash_useindialog](https://user-images.githubusercontent.com/25998847/28257811-0901534e-6b00-11e7-9e4e-44c6b243b344.png)
it's use in dialog  crash at click 

and it's the log
![logcat](https://user-images.githubusercontent.com/25998847/28257830-2a075430-6b00-11e7-979c-ab2e9c0751b4.png)
@arcadefire

**Comment by hanmeimei888** [comment]
I solve this problem, i'll  submit a modify version later (After i finnish the project on hand

**Comment by kcjian** [comment]
问题解决了吗？

**Comment by hanmeimei888** [comment]
@kcjian 解决了   你如果只是想不崩溃的话 setArrowDrawable 调用一下就可以了 不过后续还有一些问题..我是直接down下来改这个项目代码的 (ps: 改完之后觉得在dialog中使用spinner的需求貌似不是很合理 ..

**Comment by tanghaidev** [comment]
@Override
    protected void onVisibilityChanged(View changedView, int visibility) {
        super.onVisibilityChanged(changedView, visibility);
        arrowDrawable = initArrowDrawable(arrowDrawableTint);
        setArrowDrawableOrHide(arrowDrawable);
    }
问题在这  有的情况下没有触发 放到init方法就好了

**Comment by m0aaz** [comment]
in xml  set 
```
app:hideArrow="true"
```

**Comment by arcadefire** [comment]
This should be solved in #104.
