### ISSUE TITLE
how to change the border and border color with NiceSpinner

### ISSUE THREAD

**Issue by GitCod-Man** [arcadefire/nice-spinner#48]
I want to changge the NiceSpinner's border ,and i try to set the background with shape.xml ,but it didn't work!
    <org.angmarch.views.NiceSpinner
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:spinnerMode="dialog"
        android:id="@+id/nice_spinner"
        android:layout_gravity="center"
        android:background="@drawable/edittext_shape"
        android:layout_marginRight="20dp"
        android:layout_marginLeft="20dp"
        android:layout_marginTop="20dp"
        />

**Comment by JiangShuLiang** [comment]
could you tell me how to change the border's color,thx a lot
