### ISSUE TITLE
TintContextWrapper cannot be cast to Activity

### ISSUE THREAD

**Issue by YeungRay** [arcadefire/nice-spinner#53]
in measureDisplayHeight method， Activity activity = (Activity)this.getContext(), this code is wrong ,as NiceSpinner extends AppCompatTextView,so context is wrapper by TintContextWrapper .

**Comment by archerLj** [comment]
I got the same problem.

**Comment by hibob224** [comment]
@YeungRay @archerLj try updating to the latest release (1.3.1), think this will be fixed by https://github.com/arcadefire/nice-spinner/pull/54
