### ISSUE TITLE
Spinner doesn't expand upwards.

### ISSUE THREAD

**Issue by abhriyaroy** [arcadefire/nice-spinner#55]
I have a basic view, where the spinner is inside the relative layout and is at the bottom of the screen but the spinner doesn't expand upwards. I placed the nice-spinner and the default android spinner side by side in the same layout for comparison. The default spinner expands upwards but the nice-spinner doesn't. Please help.

Here is my layout -
  
         <?xml version="1.0" encoding="utf-8"?>
         <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          tools:context="com.example.royab.myapplication.MainActivity">

    <org.angmarch.views.NiceSpinner
        android:id="@+id/bitmap_selection_spinner"
        android:layout_width="150dp"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true" />

    <Spinner
        android:id="@+id/spinner2"
        android:layout_width="150dp"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"></Spinner>

     </RelativeLayout>

And here is the acitivity 

     ```
 public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        NiceSpinner niceSpinner = (NiceSpinner) findViewById(R.id.bitmap_selection_spinner);
        List<String> dataset = new LinkedList<>(Arrays.asList("One", "Two", "Three", "Four", "Five"));
        niceSpinner.attachDataSource(dataset);


        Spinner spinner2 = (Spinner) findViewById(R.id.spinner2);
        List<String> list = new ArrayList<String>();
        list.add("list 1");
        list.add("list 2");
        list.add("list 3");
        ArrayAdapter<String> dataAdapter = new ArrayAdapter<String>(this,
                android.R.layout.simple_spinner_item, list);
        dataAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        spinner2.setAdapter(dataAdapter);
    }
}






Here's what it looks like - https://imgur.com/VB2VUuZ

Please help.

**Comment by arcadefire** [comment]
This was fixed in one of the last releases.
