### ISSUE TITLE
how to change the border and border color with NiceSpinner

### ISSUE THREAD

**Issue by jonydan888** [arcadefire/nice-spinner#58]
Is this problem fixed? The use of the background property does not set the border and border style

**Comment by arcadefire** [comment]
Hey @jonydan888. 
I didn't have any time to work on this project recently. If you find a solution for it, PRs are well accepted. :)

**Comment by jonydan888** [comment]
I checked the source code, try to modify the selector, but it seems not to be successful, all the settings seem to be the selector covered, setBackgroundResoure method to get rid of the init method, and backgroundSelector settings, the background property will come into effect.
Another problem is that manually setting height will lead to incomplete content display. In fact, this problem is caused by the death of setPadding method in init method. If this property can be set flexibly, it will be better. I modified the value of padding.
