### ISSUE TITLE
联动的话，第一个spinner点击去刷新第二个的时候箭头默认是朝上的

### ISSUE THREAD

**Issue by passself** [arcadefire/nice-spinner#64]
比如第一个spinner是省，第二个表示市，点击第一个省后第二个市的spinner箭头图标是朝上的。
默认的是first.setSelectedIndex(0);和sencond.setSelectedIndex(0);

**Comment by passself** [comment]
it's same with issues 35

**Comment by wbr224869** [comment]
这个问题解决了吗
