### ISSUE TITLE
How Can I get Selected Item?

### ISSUE THREAD

**Issue by behiunforgiven** [arcadefire/nice-spinner#66]
How can I get Selected Item not Selected Index?

**Comment by ZorgeR** [comment]
I used myAttachedDataSource.get(i)

**Comment by thealpha** [comment]
same problem here

**Comment by thealpha** [comment]
he is an asshole he is not replying to anybody ....fuck your spinner ...bitch

**Comment by iammannan** [comment]
nicespinner.getSelectedItem()

**Comment by toton6868** [comment]
.getSelectedItem() is not working

**Comment by blueskky** [comment]
add the method in  NiceSpinner.java

public Object getSelectedItem() {
        return adapter.getItemInDataset(selectedIndex);
    }

**Comment by arunavo4** [comment]
Creating the Spinner
```
List<String> dataset = new LinkedList<>(Arrays.asList("University", "College", "Department", "Semester"));
Spinner.attachDataSource(dataset);
```

Now use the selected position to get the corresponding element from the list
```
Spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
                @Override
                public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                    Log.d("Spinner",dataset.get(position));   //use the position to get the element from the list
                   //Do your thing here
                }

                @Override
                public void onNothingSelected(AdapterView<?> parent) {
                    Log.d("Spinner","Nothing Selected!");
                }
            });
```

**Comment by github0null** [comment]
**the param "parent" is a class extends from ListView, so we can get the item from adapter**

@Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        ListView listView = ListView.class.cast(parent);
        ListAdapter adapter = listView.getAdapter();
        YourType item = (YourType)adapter.getItem(position);
        .......
 }

![捕获](https://user-images.githubusercontent.com/43022536/55671068-74e97c00-58be-11e9-807d-987d6eb224a6.PNG)

**Comment by arcadefire** [comment]
You can use `NiceSpinner` method: `getSelectedItem`.
