### ISSUE TITLE
invisible problem

### ISSUE THREAD

**Issue by 18payam** [arcadefire/nice-spinner#72]
Hi.
I have a problem with this library:
when i make it invisible from layout file, my app will be crashed.
i used this code:

`                    <org.angmarch.views.NiceSpinner
                        android:id="@+id/spinner_setting_font_pick"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_margin="5dp"
                        android:visibility="invisible"
                        />`

**Comment by arcadefire** [comment]
Cannot reproduce this.
