### ISSUE TITLE
Support for Custom view inside Spinner ?

### ISSUE THREAD

**Issue by Zulqurnain** [arcadefire/nice-spinner#73]
this view looks awesome , but the problem is i can't set custom view like row item , and with custom model , are you going to implement the feature in future or it is already there ?

**Comment by balakzde** [comment]
I have the same problem. I need to be able to change background color of row programatically and NiceSpinner seems to ignore my view inside of custom ArrayAdapter which I created

**Comment by arcadefire** [comment]
This option is not supported right now, but feel free to open a PR.
