### ISSUE TITLE
How to set the background color for the nice spinner? 

### ISSUE THREAD

**Issue by SpamhaterAlex** [arcadefire/nice-spinner#75]
Hi, 

I am using the "nice" spinner and in my opinion it is really nice. 
But I can not change the background color... 

When I try to set it in the xml layout for it, it will contain still the same color, its white. 

Does anybody know, how to change the background color? Or found a way for it? 

I would be very happy to know it. 

Thanks in advance

**Comment by SpamhaterAlex** [comment]
I set it programmatically, and it worked fine!

**Comment by Alameen688** [comment]
How?
