### ISSUE TITLE
How to set background if item is pressed? 

### ISSUE THREAD

**Issue by SpamhaterAlex** [arcadefire/nice-spinner#76]
Hi, 

I am looking for a way to set the background of an item, which is pressed.   
Is there a easy way to customize it with this library? 

Thanks

**Comment by muhrifqii** [comment]
I'm afraid there's no easier way other than adding attribute reference of background selector

**Comment by arunavo4** [comment]
simply use a selector in the background reference in xml and the inside selector give separate drawable resource for the two states

**Comment by arcadefire** [comment]
You can use a `backgroundSelector`. Take a look at the sample project to find out how to use it.
