### ISSUE TITLE
请问在哪里改成向上弹出呢？

### ISSUE THREAD

**Issue by Marlborn** [arcadefire/nice-spinner#82]

**Comment by Marlborn** [comment]
下午看了下改过了，-(displayHeight - getParentVerticalOffset() - getMeasuredHeight())

**Comment by KunKevin** [comment]
请问这个是怎么改的，可以实现吗？谢谢1

**Comment by Marlborn** [comment]
> 请问这个是怎么改的，可以实现吗？谢谢1

measurePopUpDimension()这个方法里
        int widthSpec = MeasureSpec.makeMeasureSpec(getMeasuredWidth(), MeasureSpec.EXACTLY);
        int temp = displayHeight - getParentVerticalOffset() - getMeasuredHeight();
        if (temp > 0) {
            temp = temp * -1;
        }
        int heightSpec = MeasureSpec.makeMeasureSpec(temp,
                MeasureSpec.AT_MOST);
        listView.measure(widthSpec, heightSpec);
