### ISSUE TITLE
bug with two spinner in layout

### ISSUE THREAD

**Issue by LaymanInCoding** [arcadefire/nice-spinner#86]
when I add two spinner in my layout file ,  I click one spinner ,the other spinner's arrow animate a little ,

**Comment by androidlab** [comment]
Did you find any solution to this? I have two spinners in my layout. When I click one of the spinners, both the arrows animate abnormally.

**Comment by cailei1** [comment]
i am also

**Comment by arcadefire** [comment]
This should be fixed in this commit: 9e18b1f35f5d7017e3affe34e73b37e02c97ba2b.
