### ISSUE TITLE
Text is centered in popup

### ISSUE THREAD

**Issue by Nickolas981** [arcadefire/nice-spinner#99]
![image](https://user-images.githubusercontent.com/17518947/49292287-886e7b80-f4b5-11e8-8d55-4738a9c0097c.png)

**Comment by arcadefire** [comment]
Hello there. I've added an attribute to change the default text alignment in the xml. Check this commit: e6c0279ff5f6548af53c63b71fc441772d5b4ae0.

You can find how to use this in the updated doc. Make sure you've downloaded the latest version of the widget.
